######################################################################################
# emart-frontend-service
######################################################################################
apiVersion: v1
kind: Service
metadata:
  name: emart-frontend
  labels:
    app: emart-frontend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: 8080-http
  selector:
    app: emart-frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: emart-frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: emart-frontend
        version: v1
    spec:
      containers:
      - name: emart-frontend
        image: image-registry.openshift-image-registry.svc:5000/cicd/emart-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
    
---
##########create route #####
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: emart-frontend
  name: emart-frontend
spec: 
  port: 
    targetPort: 8080-http
  to:
    kind: Service
    name: emart-frontend
    weight: 100
